account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path("dashboard", views.dashboard, name="dashboard"),
    path("", views.account_view, name="account"),
    path("kyc-reg/", views.kyc_registration, name="kyc-reg"),
]

core/urls.py
from django.urls import path
from core import views
from core import transfer,payment_requests,transaction,views,credit_card

app_name = "core"

urlpatterns = [
        path("", views.index, name="index"),

        # transfers
        path("search-account/", transfer.search_user_by_account_number, name = "search-account" ),
        path("amount-transfer/<account_number>/", transfer.AmountTransfer, name = "amount-transfer" ),
        path("amount-transfer-process/<account_number>/", transfer.AmountTransferProcess, name = "amount-transfer-process" ),
        path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.TransferConfirmation, name = "transfer-confirmation" ),
        path("transfer-process/<account_number>/<transaction_id>/", transfer.TransferProcess, name = "transfer-process" ),
        path("transfer-completed/<account_number>/<transaction_id>/", transfer.TransferCompleted, name = "transfer-completed" ),

        # transactions
        path('transactions/', transaction.transaction_lists, name='transactions'),
        path('transaction-detail/<transaction_id>/', transaction.transaction_detail, name='transaction-detail'),

        # Request Payments
        path('search-user-account/', payment_requests.SearchUserRequest, name='search-user-account'),

        path('amount-request/<account_number>/', payment_requests.AmountRequest, name='amount-request'),

        path('amount-request-process/<account_number>/', payment_requests.AmountRequestProcess, name='amount-request-process'),

        path('amount-request-process-confirmation/<account_number>/<transaction_id>/', payment_requests.AmountRequestConfirmation, name='amount-request-process-confirmation'),

        path('amount-request-final-process/<account_number>/<transaction_id>/', payment_requests.AmountRequestFinalProcess, name='amount-request-final-process'),

        path('amount-request-completed/<account_number>/<transaction_id>/', payment_requests.RequestCompleted, name='amount-request-completed'),

        # Request Settlement
        path("settlement-confirmation/<account_number>/<transaction_id>/", payment_requests.settlement_confirmation, name="settlement-confirmation"),
        path("settlement-processing/<account_number>/<transaction_id>/", payment_requests.settlement_processing, name="settlement-processing"),
        path("settlement-completed/<account_number>/<transaction_id>/", payment_requests.SettlementCompleted, name="settlement-completed"),
        path("delete-payment-request/<account_number>/<transaction_id>/", payment_requests.DeletePaymentRequest, name="delete-payment-request"),


        # Credit Card Handling
        path("credit-card-details/<card_id>/", credit_card.credit_card_details, name="credit-card-details"),
        path("fund-credit-card/<card_id>/", credit_card.fund_credit_card, name="fund-credit-card"),
        path("withraw_fund_from_card/<card_id>/", credit_card.withraw_fund_from_card ,name="withraw_fund_from_card"),
        path("delete_credit_card/<card_id>/", credit_card.delete_credit_card ,name="delete_credit_card"),
]

daniel_pay_wise/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauth.urls")),
    path("account/", include("account.urls"))
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views

app_name = "userauth"

urlpatterns = [
    path("register/", views.RegisterUserView, name="register-user"),
     path("login/", views.LoginUserView, name="login-user"),
    path("logout/", views.logoutUserView, name="logout-user")
]

templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>D-Pay wiser - Banking Beyond Boundaries</title>
    <link rel="shortcut icon" href="{% static 'assets/images/fav1.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/arafat-font.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body>

    <a href="javascript:void(0)" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>

   <!-- header-section start -->
    <header class="header-section">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex header-area">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="/">
                            <img src="{% static 'assets/images/logo-1.png'%}" class="logo" alt="logo">
                        </a>
                        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbar-content">
                            <i class="fas fa-bars"></i>
                        </button>
                        <div class="collapse navbar-collapse justify-content-end" id="navbar-content">
                            {% comment %} <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Personal</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="payments-01.html">Freelancer Payments</a></li>
                                        <li><a class="nav-link" href="subscriptions.html">Subscriptions</a></li>
                                        <li><a class="nav-link" href="security.html">Security</a></li>
                                        <li><a class="nav-link" href="fees.html">Fees</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Business</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="payments-01.html">Business Payments</a></li>
                                        <li><a class="nav-link" href="business-account.html">Business Account</a></li>
                                        <li><a class="nav-link" href="corporate-card.html">Corporate Card</a></li>
                                        <li><a class="nav-link" href="expense-management.html">Expense Management</a></li>
                                        <li><a class="nav-link" href="budgeting-and-analytics.html">Budgeting</a></li>
                                        <li><a class="nav-link" href="integrations.html">Integrations</a></li>
                                        <li><a class="nav-link" href="invoice-management.html">Invoice</a></li>
                                        <li><a class="nav-link" href="security.html">Security</a></li>
                                        <li><a class="nav-link" href="rewards.html">Rewards</a></li>
                                        <li><a class="nav-link" href="fees.html">Fees</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Company</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="about-us.html">About Us</a></li>
                                        <li><a class="nav-link" href="career.html">Career</a></li>
                                        <li><a class="nav-link" href="career-details.html">Career Details</a></li>
                                        <li class="dropend sub-navbar">
                                            <a href="javascript:void(0)" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown"
                                              data-bs-auto-close="outside">Blog</a>
                                            <ul class="dropdown-menu sub-menu shadow">
                                                <li><a class="nav-link" href="blog.html">Blog</a></li>
                                                <li><a class="nav-link" href="blog-details.html">Blog Details</a></li>
                                            </ul>
                                        </li>
                                        <li><a class="nav-link" href="error.html">Error</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="javascript:void(0)"
                                        data-bs-toggle="dropdown" data-bs-auto-close="outside">Help</a>
                                    <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="help-center.html">Help Center</a></li>
                                        <li><a class="nav-link" href="help-center-category.html">Help Category</a></li>
                                    </ul>
                                </li>
                            </ul> {% endcomment %}
                            <div class="right-area header-action d-flex align-items-center max-un">
                            {% if request.user.is_authenticated %}
                                    <a href="/admin" class="cmn-btn">Admin</a>
                                    <a href="{% url "userauth:logout-user" %}" class="cmn-btn">Logout</a>
                            {% else %}
                                    <a href="{% url "userauth:login-user" %}" class="login">Login</a>
                                    <a href="{% url "userauth:register-user" %}" class="cmn-btn">Sign Up
                                    <i class="fa fa-arrow-right"></i>
                                    </a>
                            {% endif %}
                            </div>
                        </div>
                    </nav>
                </div>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong> {{message}}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </header>
    <!-- header-section end -->
{% block content %}

{% endblock content %}
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/fontawesome.js' %}"></script>
    <script src="{% static 'assets/js/plugin/slick.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/counter.js' %}"></script>
    <script src="{% static 'assets/js/plugin/waypoint.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/plugin.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

templates/partials/dashboard-base.html
{% load static %} <!-- Make sure this line is at the top of your template -->

<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>D-Pay wiser Banking Beyond Boundaries</title>
    <link rel="shortcut icon" href="{% static 'assets/images/fav.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'assets1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets1/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets1/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'assets1/css/plugin/apexcharts.css' %}">
    <link rel="stylesheet" href="{% static 'assets1/css/plugin/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets1/css/arafat-font.css' %}">
    <link rel="stylesheet" href="{% static 'assets1/css/plugin/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets1/css/style.css' %}">
</head>

<body>
    <!-- start preloader -->
    {% comment %} <div class="preloader" id="preloader"></div> {% endcomment %}
    <!-- end preloader -->

    <!-- Scroll To Top Start-->
    <a href="javascript:void(0)" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>
    <!-- Scroll To Top End -->

    <!-- header-section start -->
    <header class="header-section body-collapse">
        <div class="overlay">
            <div class="container-fruid">
                <div class="row d-flex header-area">
                    <div class="navbar-area d-flex align-items-center justify-content-between">
                        <div class="sidebar-icon">
                            <img src="{% static 'assets1/images/icon/menu.png' %}" alt="icon">
                        </div>
                        <form method="POST" class="flex-fill"> 
                            <div class="form-group d-flex align-items-center">
                                <img src="{% static 'assets1/images/icon/search.png' %}" alt="icon">
                                <input type="text" placeholder="Type to search...">
                            </div>
                        </form>
                        <div class="dashboard-nav">
                            <div class="single-item language-area">
                                <div class="language-btn">
                                    <img src="{% static 'assets1/images/icon/lang.png' %}" alt="icon">
                                </div>
                                <ul class="main-area language-content">
                                    <li>English</li>
                                    <li>Hindi</li>
                                    <li class="active">English (US)</li>
                                    <li>Japanese</li>
                                    <li>Kannada</li>
                                    <li>Lithuanian</li>
                                </ul>
                            </div>
                            <div class="single-item notifications-area">
                                <div class="notifications-btn">
                                    <img src="{% static 'assets1/images/icon/bell.png' %}" class="bell-icon" alt="icon">
                                </div>
                                <div class="main-area notifications-content">
                                    <div class="head-area d-flex justify-content-between">
                                        <h5>Notifications</h5>
                                        <span class="mdr">4</span>
                                    </div>
                                    <ul>
                                        <li>
                                            <a href="javascript:void(0)" class="d-flex">
                                                <div class="img-area">
                                                    <img src="{% static 'assets1/images/user-1.png' %}" class="max-un" alt="image">
                                                </div>
                                                <div class="text-area">
                                                    <p class="mdr">You received a payment of <b>$134.00</b> from <b>Anna
                                                            Green</b></p>
                                                    <p class="mdr time-area">09.39AM</p>
                                                </div>
                                            </a>
                                            <i class="fa-solid fa-caret-right"></i>
                                        </li>
                                        <!-- Rest of your notifications here -->
                                    </ul>
                                </div>
                            </div>
                            <div class="single-item user-area">
                                <div class="profile-area d-flex align-items-center">
                                <span class="user-profile">
                                    {% if kyc.image.url %}
                                            <img style="width:40px; height:40px; border-radius: 50%; object-fit: cover;" src="{{ kyc.image.url }}" alt="profile">
                                    {% else %}
                                            <img style="width:40px; height:40px; border-radius: 50%; object-fit: cover;" src="{% static 'assets1/images/default.jpg' %}" alt="profile">
                                    {% endif %}
                                    </span>
                                    <i class="fa-solid fa-sort-down"></i>
                                </div>
                                <div class="main-area user-content">
                                    <div class="head-area d-flex align-items-center">
                                        <div class="profile-img">
                                            {% if kyc.image.url %}
                                            <img style="width:40px; height:40px; border-radius: 50%; object-fit: cover;" src="{{ kyc.image.url }}" alt="profile">
                                            {% else %}
                                            <img style="width:40px; height:40px; border-radius: 50%; object-fit: cover;" src="{% static 'assets1/images/default.jpg' %}" alt="profile">
                                            {% endif %}
                                        </div>
                                        <div class="profile-head">
                                            <a href="{% url 'account:account' %}">
                                                <h5>{{kyc.full_name}}</h5>
                                            </a>
                                            <p class="wallet-id"><small>Account No: {{account.account_number}}<small/></p>
                                            <p class="wallet-id"><small>Pin No: {{account.account_pin_number}}<small/></p>
                                        </div>
                                    </div>
                                    <ul>
                                    <li class="border-area">
                                            <a href="/admin/"><i class="fas fa-user"></i>Admin</a>
                                        </li>
                                        <li class="border-area">
                                            <a href="account.html"><i class="fas fa-cog"></i>Settings</a>
                                        </li>
                                        <li>
                                            <a href="{% url "userauth:logout-user"%}"><i class="fas fa-sign-out"></i>Logout</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sidebar-wrapper">
                    <div class="close-btn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                    <div class="sidebar-logo">
                        <a href="dashboard.html"><img src="{% static 'assets/images/logo-1.png' %}" alt="logo"></a>
                    </div>
                <ul>
                    <li class="active">
                        <a href="{% url "account:dashboard"%}">
                            <i class="fas fa-tachometer-alt"></i> <span style="margin-left:10px">Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url "core:transactions"%}">
                            <i class="fas fa-exchange-alt"></i> <span style="margin-left:10px">Transactions</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'core:search-account' %}">
                            <i class="fas fa-money-bill-wave"></i> <span style="margin-left:10px">Pay</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'core:search-user-account' %}">
                            <i class="fas fa-hand-holding-usd"></i> <span style="margin-left:10px">Receive</span>
                        </a>
                    </li>
                    {% comment %} <li>
                        <a href="/account/dashboard">
                            <i class="fas fa-exchange-alt"></i> <span style="margin-left:10px" >Exchange</span>
                        </a>
                    </li> {% endcomment %}
                    {% comment %} <li>
                        <a href="/account/dashboard">
                            <i class="fas fa-users"></i> <span style="margin-left:10px">Recipients</span>
                        </a>
                    </li> {% endcomment %}
                    {% comment %} <li>
                        <a href="/account/dashboard">
                            <i class="fas fa-globe fa-lg"></i> <span style="margin-left:10px">Crypto</span>
                        </a>
                    </li> {% endcomment %}
                    <li>
                        <a href="/account/dashboard">
                            <i class="fas fa-money-check-alt"></i> <span style="margin-left:10px">Deposit Money</span>
                        </a>
                    </li>
                    {% comment %} <li>
                        <a href="withdraw-money-step-1.html">
                            <i class="fas fa-money-bill-wave"></i> <span style="margin-left:10px">Withdraw Money</span>
                        </a>
                    </li> {% endcomment %}
                    <!-- Add more sidebar items here -->
                </ul>
                <ul class="bottom-item">
                    <li>
                        <a href="{% url 'account:account' %}">
                            <i class="fas fa-user-circle"></i> <span style="margin-left:10px">Account</span>
                        </a>
                    </li>
                    {% comment %} <li>
                        <a href="/account/dashboard">
                            <i class="fas fa-life-ring"></i> <span style="margin-left:10px">Support</span>
                        </a>
                    </li> {% endcomment %}
                    <li>
                        <a href="{% url 'userauth:logout-user' %}">
                            <i class="fas fa-power-off text-danger"></i> <span style="margin-left:10px">Quit</span>
                        </a>
                    </li>
                </ul>
                    <div class="pt-120">
                        <div class="invite-now">
                            <div class="img-area">
                                <img src="{% static 'assets1/images/invite-now-illus.png' %}" alt="Image">
                            </div>
                            <p>Invite your friend and get $25</p>
                            <a href="javascript:void(0)" class="cmn-btn">Invite Now</a>
                        </div>
                    </div>
                </div>
                </div>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong> {{message}}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </header>
    <!-- header-section end -->
    {% block content %}
    {% endblock content %}

    <!-- JavaScript files -->
    <script src="{% static 'assets1/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets1/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets1/js/jquery-ui.js' %}"></script>
    <script src="{% static 'assets1/js/plugin/apexcharts.js' %}"></script>
    <script src="{% static 'assets1/js/plugin/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets1/js/plugin/waypoint.min.js' %}"></script>
    <script src="{% static 'assets1/js/plugin/wow.min.js' %}"></script>
    <script src="{% static 'assets1/js/plugin/plugin.js' %}"></script>
    <script src="{% static 'assets1/js/main.js' %}"></script>
</body>

</html>