core/urls.py
from django.urls import path
from core import views
from core import transfer,payment_requests,transaction,views,credit_card

app_name = "core"

urlpatterns = [
        path("", views.index, name="index"),

        # transfers
        path("search-account/", transfer.search_user_by_account_number, name = "search-account" ),
        path("amount-transfer/<account_number>/", transfer.AmountTransfer, name = "amount-transfer" ),
        path("amount-transfer-process/<account_number>/", transfer.AmountTransferProcess, name = "amount-transfer-process" ),
        path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.TransferConfirmation, name = "transfer-confirmation" ),
        path("transfer-process/<account_number>/<transaction_id>/", transfer.TransferProcess, name = "transfer-process" ),
        path("transfer-completed/<account_number>/<transaction_id>/", transfer.TransferCompleted, name = "transfer-completed" ),

        # transactions
        path('transactions/', transaction.transaction_lists, name='transactions'),
        path('transaction-detail/<transaction_id>/', transaction.transaction_detail, name='transaction-detail'),

        # Request Payments
        path('search-user-account/', payment_requests.SearchUserRequest, name='search-user-account'),

        path('amount-request/<account_number>/', payment_requests.AmountRequest, name='amount-request'),

        path('amount-request-process/<account_number>/', payment_requests.AmountRequestProcess, name='amount-request-process'),

        path('amount-request-process-confirmation/<account_number>/<transaction_id>/', payment_requests.AmountRequestConfirmation, name='amount-request-process-confirmation'),

        path('amount-request-final-process/<account_number>/<transaction_id>/', payment_requests.AmountRequestFinalProcess, name='amount-request-final-process'),

        path('amount-request-completed/<account_number>/<transaction_id>/', payment_requests.RequestCompleted, name='amount-request-completed'),

        # Request Settlement
        path("settlement-confirmation/<account_number>/<transaction_id>/", payment_requests.settlement_confirmation, name="settlement-confirmation"),
        path("settlement-processing/<account_number>/<transaction_id>/", payment_requests.settlement_processing, name="settlement-processing"),
        path("settlement-completed/<account_number>/<transaction_id>/", payment_requests.SettlementCompleted, name="settlement-completed"),
        path("delete-payment-request/<account_number>/<transaction_id>/", payment_requests.DeletePaymentRequest, name="delete-payment-request"),


        # Credit Card Handling
        path("credit-card-details/<card_id>/", credit_card.credit_card_details, name="credit-card-details"),
        path("fund-credit-card/<card_id>/", credit_card.fund_credit_card, name="fund-credit-card"),
        path("withraw_fund_from_card/<card_id>/", credit_card.withraw_fund_from_card ,name="withraw_fund_from_card"),
        path("delete_credit_card/<card_id>/", credit_card.delete_credit_card ,name="delete_credit_card"),
]

daniel_pay_wise/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauth.urls")),
    path("account/", include("account.urls"))
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/transfer/amount-transfer.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize%}
{% block content %}
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <i class="fas fa-question-circle fa-2x"></i>
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set Amount of transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{transfer_to_account.kyc.image.url}}" style= "width:50px; height:50px; border-radius: 50%; object-fit:cover" alt="profile">
                                    </div>
                                    <div class="text-area">
                                        <p>{{transfer_to_account.kyc.full_name}}</p>
                                        <span class="mdr">{{transfer_to_account.kyc.email}}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    <a href="{% url "core:search-account"%}">
                                        <i class="icon-g-tick"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form method="POST" action={% url "core:amount-transfer-process" transfer_to_account.account_number %}>
                    {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">You Send</span>
                            <div class="input-area">
                                <input onkeyup="calculateBalance()" id="amount-send" name="amount-send" placeholder="{{request.user.transfer_to_account.account_balance| intcomma}}" type="number">
                                <select>
                                    <option value="1">USD</option>
                                    <option value="2">USD</option>
                                    <option value="3">USD</option>
                                </select>
                            </div>
                            <p>Available Balance<b>$ {{request.user.account.account_balance| intcomma}}</b></p>
                            <p id="new_balance"></p>
                            <p id="error-div" class="text-danger"></p>
                        </div>
                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Payment Description</span>
                                <input name="description" placeholder="Payment fees" type="text">
                        </div>
                        <ul class="total-fees">
                            <li>Total Fees</li>
                            <li>Free</li>
                        </ul>
                        <ul class="total-fees pay">
                            <li>
                                <h5>Total To Pay</h5>
                            </li>
                            <li>
                                <h5 id="total-to-pay">USD 0.00</h5>
                            </li>
                        </ul>
                        <div class="footer-area mt-40">
                            <a href="pay-step-1.html">Previous Step</a>
                            <button style="padding:10px 30px; border-radiuyou communicacs:10px; background:rgb(98,0,255);color:#fff"  type= "submit"class="active">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    {% comment %} Javascript methods {% endcomment %}
<script>
function calculateBalance() {
    // Get current account balance for the user
    let availableBalance = parseFloat("{{ request.user.account.account_balance }}");
    let newBalanceElement = document.getElementById("new_balance");
    let sendAmountInput = document.getElementById("amount-send");
    let sendAmount = parseFloat(sendAmountInput.value);

    let errorDiv = document.getElementById("error-div");
    let totalToPay = document.getElementById("total-to-pay");

    if (isNaN(availableBalance) || isNaN(sendAmount)) {
        errorDiv.innerHTML = "Please enter valid numeric values.";
        return;
    }

    let calculatedNewBalance = availableBalance - sendAmount;

    if (calculatedNewBalance < 0) {
        newBalanceElement.style.color = "red";
        errorDiv.innerHTML = "You can only send up to $" + availableBalance.toLocaleString();
    } else {
        newBalanceElement.style.color = "green";
        errorDiv.innerHTML = "";
    }

    newBalanceElement.innerHTML = `Remaining balance is: <b>$${calculatedNewBalance.toLocaleString()}</b>`;
    totalToPay.innerHTML = `USD: <b>$${sendAmount.toLocaleString()}</b>`;
}
</script>
 {% endblock content %}

templates/transfer/transfer-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize%}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <i class="fas fa-question-circle fa-2x"></i>
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>Submitted</h3>
                            <p>Payment <b>{{transaction.transaction_id}}</b> was sent to <b>{{account.user.kyc.full_name}}</b></p>
                            <h5><a href=""><b>View Details</b></a>| <a href=""> <b>another Payment</b></a></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/transfer/transfer-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize%}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <i class="fas fa-question-circle fa-2x"></i>
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{transfer_to_account.kyc.image.url}}" style= "width:50px; height:50px; border-radius: 50%; object-fit:cover" alt="profile">
                                    </div>
                                    <div class="text-area">
                                        <p>{{transfer_to_account.kyc.full_name}}</p>
                                        <span class="mdr">{{transfer_to_account.kyc.email}}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    <a href="{% url "core:search-account"%}">
                                        <i class="icon-g-tick"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Payment Details</h6>
                            <div class="right">
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    Edit
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>You Send</span>
                                        <b>{{transaction.amount}} USD</b>
                                    </li>
                                    <li>
                                        <span>Recipient gets</span>
                                        <b>{{transaction.amount}} USD</b>
                                    </li>
                                    <li>
                                        <span>E-mail of receiver</span>
                                        <b>{{transfer_to_account.user.email}}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Purpose | Description</span>
                                        <b>{{transaction.description}}</b>
                                    </li>
                                    <li>
                                        <span>Transfer initiated on:</span>
                                        <b>{{transaction.date}}</b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the payment details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="pay-step-2.html">Previous Step</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Pay</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                                <h4>Confirm Transfer!</h4>
                                                <p>We have sent a verification code to your phone <span>+44831***932</span>. Please enter the verification code below.</p>
                                                <form method="POST" action="{% url 'core:transfer-process' transfer_to_account.account_number transaction.transaction_id  %}">
                                                    {% csrf_token %}
                                                    <div class="userInput">
                                                        <input minlength="4" maxlength="4" type="text" name="pin-number">
                                                    </div>
                                                    <a href="javascript:void(0)">Don’t receive a code?</a>
                                                    <button type="submit" class="mt-60 confirm">Confirm</button>
                                                </form>
                                            </div>

                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <img src="{% static 'assets1/images/icon/success.png' %}" alt="icon">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}